Support for control-plane volume snapshots

diff --git a/k8s/eksd/eksd-terraform/modules/asg/files/cloudinit-server.template.yaml b/k8s/eksd/eksd-terraform/modules/asg/files/cloudinit-server.template.yaml
--- a/k8s/eksd/eksd-terraform/modules/asg/files/cloudinit-server.template.yaml
+++ b/k8s/eksd/eksd-terraform/modules/asg/files/cloudinit-server.template.yaml
@@ -37,9 +37,49 @@ write_files:
       echo "`date`: ETCD backup - started"
 
       BACKUP_ROTATION=${ backup_rotation } # multi-masters parallelism will likely make it a bit lower
+      if [ ! $BACKUP_ROTATION -gt 0 ]; then
+          echo "`date`: ETCD backup - disabled per non-positive rotation value"
+          exit 0
+      fi
+      
+      api_endpoint="$(curl -s http://169.254.169.254/openstack/latest/meta_data.json | jq -c '.cluster_url' | cut -d\" -f2)"
 
       shopt -s expand_aliases
       alias kubectl="kubectl --kubeconfig=/etc/kubernetes/admin.conf --namespace kube-system"
+      alias ec2="aws ec2 --endpoint-url $api_endpoint/api/v2/aws/ec2"
+
+      host_name="$(hostname)"
+      host_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
+      cluster_name="${ cluster_name }"
+      cluster_certificate="${ certificate }" # the only "real" unique cluster identifier
+      cluster_id=$${cluster_certificate:0:7}
+      local_filename='etcd_backup_'$host_name'_'$host_id'.db'
+
+      echo "`date`: ETCD backup - saving locally to /etc/kubernetes/zadara/$local_filename"
+      ETCDCTL_API=3 etcdctl \
+          --endpoints=https://localhost:2379 \
+          --cacert=/etc/kubernetes/pki/etcd/ca.crt \
+          --key=/etc/kubernetes/pki/etcd/peer.key \
+          --cert=/etc/kubernetes/pki/etcd/peer.crt \
+          snapshot save "/etc/kubernetes/zadara/$local_filename"
+
+      echo "`date`: ETCD backup - snapshotting boot volume"
+      volume=$(ec2 describe-volumes --filters Name=attachment.instance-id,Values=$host_id --query 'Volumes[0].VolumeId' | cut -d\" -f2)
+      ec2 create-snapshot \
+          --volume-id $volume \
+          --description "Automated snapshot of EKS-D control-plane boot drive (containing ETCD)" \
+          --tag-specifications 'ResourceType=snapshot,Tags=[{Key=Name,Value=EKS-D_autosnap_'$host_name'},{Key=managed-by,Value='$cluster_name'}]'
+      if [ $? -ne 0 ]; then
+          echo "`date`: ETCD backup - error while snapshotting (run manually to see the exact issue), exiting with error"
+          exit 1
+      fi
+
+      while [ $(ec2 describe-snapshots --filter "Name=tag:managed-by,Values=c-k8s" --query 'Snapshots[*].SnapshotId | length(@)') -gt $BACKUP_ROTATION ]
+      do
+          oldest=$(ec2 describe-snapshots --filter "Name=tag:managed-by,Values=c-k8s" --query 'sort_by(Snapshots, &StartTime)[0].SnapshotId' | cut -d\" -f2)
+          echo "`date`: ETCD backup - attempting to purge snapshot $oldest"
+          ec2 delete-snapshot --snapshot-id $oldest
+      done
 
       secret=$(kubectl get secret zadara-backup-export -o name)
       if [ -n "$secret" ]; then
@@ -59,21 +99,6 @@ write_files:
       if [ -z "$(echo $AWS_ENDPOINT_URL)" ]; then
           unset AWS_ENDPOINT_URL  #real AWS S3 will not use endpoint
       fi
-
-      host_name="$(hostname)"
-      host_id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
-      cluster_name="${ cluster_name }"
-      cluster_certificate="${ certificate }" # the only "real" unique cluster identifier
-      cluster_id=$${cluster_certificate:0:7}
-      local_filename='etcd_backup_'$host_name'_'$host_id'.db'
-
-      echo "`date`: ETCD backup - saving locally to /etc/kubernetes/zadara/$local_filename"
-      ETCDCTL_API=3 etcdctl \
-          --endpoints=https://localhost:2379 \
-          --cacert=/etc/kubernetes/pki/etcd/ca.crt \
-          --key=/etc/kubernetes/pki/etcd/peer.key \
-          --cert=/etc/kubernetes/pki/etcd/peer.crt \
-          snapshot save "/etc/kubernetes/zadara/$local_filename"
 
       if [[ -z "$(echo $AWS_ACCESS_KEY_ID)" || -z "$(echo $AWS_SECRET_ACCESS_KEY)" || -z "$(echo $AWS_REGION)" || -z "$BUCKET" ]]; then
           echo "`date`: ETCD backup - finished (without export - skipped due to missing S3 information)"
